In [ ]:
#SINGLE QUOTES STRING
my_sub='machine learning'
type(my_sub)


str

In [ ]:
#double quotes string
my_sub="my college"
type(my_sub)

str

In [ ]:
#triple qoutes string
my_sub="""this sentence is a multiple line,
this is also known as string"""
type(my_sub)

str

In [ ]:
#find the lenght of string
my_sub=="machine learning"
len(my_sub)

62

In [ ]:
#indexing of string
my_sub= "machine learning"
print(my_sub[6])

e


In [ ]:
#negative indexing
my_sub= "machine learning"
print(my_sub[-11])

n


In [ ]:
#slicing
print(my_sub[0:7])

machine


In [ ]:
#lower()--htis method used to convert string into lower case
my_sub.lower()

'machine learning'

In [ ]:
#upper()--this method used to convert string into upper case
my_sub.upper()

'MACHINE LEARNING'

In [ ]:
#count()--this method count particular character in string
my_sub.count('l')

1

In [ ]:
#list--it is a collecction of items whuch is separated by , (comma) all item are enclosed by square bracket
my_list=[23,45,67,89]
type(my_list)


list

In [ ]:
mixed_list=[23,54,"apple",None]
type(mixed_list)

list

In [ ]:
# indexing in list-->location of item
# two types=pos. & neg.


In [ ]:
#positive indexing
my_list=[34,54,67,54]
print(my_list[1])
print(my_list[2])

54
67


In [ ]:
#negative indexing
my_list=[34,54,67,54]
print(my_list[-1])
print(my_list[-2])

54
67


In [ ]:
#slicing in list-->to grab data from a designated point
my_list=[34,54,67,54,67,89]
my_list[0:5:1]

[34, 54, 67, 54, 67]

In [ ]:
my_list=[34,54,67,54,67,89]
my_list[0:5]

[34, 54, 67, 54, 67]

In [ ]:
my_list=[34,54,67,54,67,89]
my_list[:5]

[34, 54, 67, 54, 67]

In [ ]:
#function in list
#min()-- return minimum num. of the list
my_list=[34,54,67,54,67,89]
min(my_list)

34

In [ ]:
#max()--return maximum of of the list
my_list=[34,45,65,34,56]
max(my_list)

65

In [ ]:
#sum()--return sum of all numbers in the list
my_list=[23,34,54,65,66]
sum(my_list)

242

In [ ]:
#sorted()--this function arrange the list in inc. order (add reverse for dec.)
list1=[2,4,1,6,4,8,]
sorted(list1,reverse=True)

[8, 6, 4, 4, 2, 1]

In [ ]:
#append--this method add item at the end of the list and take itme as  argument
my_list=[34,56,76,78]
print(my_list)
my_list.append(45)
print(my_list)

[34, 56, 76, 78]
[34, 56, 76, 78, 45]


In [ ]:
my_list[2]=200
print(my_list)

[34, 56, 200, 78, 45]


In [ ]:
#extend()=--this method merge a list into another list
list1=[23,43,43,47]
list2=[54,67,89,443]
list1.extend(list2)
print(list1)

[23, 43, 43, 47, 54, 67, 89, 443]


In [ ]:
#pop()--this method remove last itme from the list,takw index as argument
my_list=[34,56,78,86]
my_list.pop()

86

In [ ]:
#remove()--this method remove item from this list but take item as a argument
list1=[34,45,4,33,67]
list1.remove(67)
print(list1)

[34, 45, 4, 33]


In [ ]:
#inverse()--this method reverse the list
my_list=[45,35,65,76]
my_list.reverse()
print(my_list)

[76, 65, 35, 45]


In [ ]:
# DICTIONARY--it is a collection of kry and value pair
# it is mutually type data structure
# the key and value is separated by colon
#the cobination of key and value is known as item and every  item is separated by comma,and all item enclosed by (curly braces){}

In [ ]:
#dictionary
my_dict= {"name":"amit","college":"shoolini"}
type(my_dict)
print(my_dict)



dict

In [ ]:
#moethod in dictionary
#keys()--this method finds the keys of dictionary
list(my_dict.keys())

['name', 'college']

In [ ]:
#values()--this method find value of dictionary
list(my_dict.values())

['amit', 'shoolini']

In [ ]:
#item()--thismethod find values of dictionary
list(my_dict.items())

[('name', 'amit'), ('college', 'shoolini')]

In [ ]:
#get--this method find value int the dictionary and key tale as argument
my_dict.get("name")

'amit'

In [ ]:
#update()--this method method update the dictionary and take dictionary as argument
my_dict{"name":amit,"college":"shoolini",}
my_dict.update({"age":25})
my_dict

SyntaxError: invalid syntax (ipython-input-1687084912.py, line 2)

In [ ]:
#conditional statement
age=int(input("enter your age-->"))
if age>18:
  print("you are eligible for marriage")
else:
  print("you are not eligible for marriage")



enter your age-->34
you are eligible for marriage


In [ ]:
age=int(input("enter age-->"))
if age>18:
  print("you are eligible for marriage")
elif age==18:
  print("you are not eligible for marriage")
else:
  print("you are not eligible for marriage")

enter age-->34
you are eligible for marriage


In [ ]:
#LOOP-->help to run a code repeatedly
my_sub="python"
for i in my_sub:
  print(i)

p
y
t
h
o
n


In [ ]:
#Range--->(sp,ep,ss)
# sp--slanting point.it is included .by default it is zero
#ending--point, it is exclude
#ss--stop size,by default it is one

In [ ]:
for i in range(0,9,1):
  print(i)

0
1
2
3
4
5
6
7
8


In [ ]:
for i in range(6):
  print(i)

0
1
2
3
4
5


In [ ]:
my_sub="python"
for i in range(len(my_sub)):
  print(my_sub[i], "-->", i)

p --> 0
y --> 1
t --> 2
h --> 3
o --> 4
n --> 5


In [ ]:
#while loop
i=0 #intializtion
while i<=10: #condition
  print(i)
  i=i+1 #increment

0
1
2
3
4
5
6
7
8
9
10


In [ ]:
#loops and control statement-->
#  break-->this statement break the loop
i=0  #intialisation
while i<5:
  i+=1 #increment
  if i==3:
    break
  else:
    print(i)

1
2


In [ ]:
#continue statement-->this statement skip the current iteration
i = 0
while i<5:
 i=i+1
 if i==3:
   continue
   print(i)
 else:
    print(i)


1
2
4
5


In [ ]:
#pass statement-->this statement pass the code
i=0
while i<5:
  i+=1
  if i==3:
    pass
    print(i)
  else:
    print(i)

1
2
3
4
5


In [ ]:
#function
#1.build in functions'
#2. user defined - it is define by user
#by def
# synatax :
# def ADD():
   #  code
   # code
   #  return

SyntaxError: invalid non-printable character U+00A0 (ipython-input-198166037.py, line 9)

In [ ]:
#user defined funtiocn witout argument
def add():
  a=int(input("enter the first neumber-->"))
  b=int(input("enter the second number-->"))
  c=a+b
  print(c)

In [ ]:
#postional argument :
def calculation(a,b):
  print("addtion",a+b)
  print ("subtraction",a-b)
  print("multiplication",a*b)
  print("division",a/b)
  return "calculation is complete-789[]"
calculation(30,20)

addtion 50
subtraction 10
multiplication 600
division 1.5


'calculation is complete-789[]'

In [ ]:
# default ARGUMENT
def area_perimeter(width=4,height=8):
  area=width*height
  perimeter=2*(width+height)
  return"area is",area,"and perimeter is",perimeter


In [ ]:
  print(area_perimeter(10,4))

('area is', 40, 'and perimeter is', 28)


In [ ]:
#keyword argument
def interest(p,r,t):
  i=(p*r*t)/100
  return i

In [ ]:
print(interest(p=1000,r=10,t=2))

200.0


In [ ]:
#variable'length argument'
#non argument  position variable lenght argument
def test(*args):
  print(args)
  print(len(args))
  print(type(args))

In [ ]:
test(2,3,4,8,9,7)

(2, 3, 4, 8, 9, 7)
6
<class 'tuple'>


In [ ]:
def sum_num(*args):
  sum=0
  for num in args:
    sum+=num
  return sum

In [ ]:
sum_num(3,5,6,7,8,9)

38

In [ ]:
def sum_num(*args):


In [ ]:
#keyword variable length argument
# '''it is behave like dictionary is is represnted by()
def test(**kwargs):
  print(kwargs)
  print(type(kwargs))
  print(len(kwargs))
test(a=1,b=2,c=3)

{'a': 1, 'b': 2, 'c': 3}
<class 'dict'>
3


In [ ]:
def pass_students(**kwargs):
  pass_student_list=[]
  for name,marks in kwargs.item():
    if marks>15:
      pass_student_list.append(name)
      return pass_student_list

NameError: name 'feg' is not defined

In [ ]:
#library-->library are the collelction of variables
#NUMPY-->

In [ ]:
import numpy as np
mat1=np.matrix("1,2,3;4,5,6;7,8,9")
print(mat1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
mat2=np.matrix([[1,2,3],[4,5,6]])
print(mat2)

[[1 2 3]
 [4 5 6]]


In [ ]:
mat3=np.random.random((3,3))
print(mat3)

[[0.9381614  0.48980294 0.54175103]
 [0.20019602 0.66435921 0.44726326]
 [0.21372333 0.59814935 0.04805706]]


In [ ]:
mat4=np.random.randint(1,20,(3,3))
print(mat4)

[[ 4  6 13]
 [ 4 15  3]
 [ 5 10 14]]


In [ ]:
zeros_array=np.zeros((3,3),dtype=int)
print(zeros_array)


[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
ones_array=np.ones((3,3),dtype=int)
print(ones_array)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
print(ones_array*100)

[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [ ]:
my_array=np.full((3,3),10)
print(my_array)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
my_array=np.array([1,2,3,4,])
print(my_array)

[1 2 3 4]


In [ ]:
power_array=np.power(my_array,2)
print(power_array)

[ 1  4  9 16]


In [ ]:
exp_array=np.exp(my_array)
print(exp_array)

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [ ]:
log_array=np.log(my_array)
print(log_array)

[0.         0.69314718 1.09861229 1.38629436]


In [ ]:
log2_array=np.log2(my_array)
print(log2_array)

[0.        1.        1.5849625 2.       ]


In [ ]:
log10_array=np.log10(my_array)
print(log10_array)

[0.         0.30103    0.47712125 0.60205999]


In [ ]:
#series---one dimensional data structure of pandas
import pandas as pd
my_series=pd.Series(["apple","mango","banana","orange"],name="Fruits")
my_series

0     apple
1     mango
2    banana
3    orange
Name: Fruits, dtype: object

In [ ]:
#dataframe--two dimensional data str of pandas
list_into_list = [["Amar",15],["Akabar",30],["Anthney",40]]
df=pd.DataFrame(list_into_list,columns=["Name","Age"])
df

Name  Age
0     Amar   15
1   Akabar   30
2  Anthney   40

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/data/imdb_data.csv")
df

id                              belongs_to_collection    budget  \
0        1  [{'id': 313576, 'name': 'Hot Tub Time Machine ...  14000000   
1        2  [{'id': 107674, 'name': 'The Princess Diaries ...  40000000   
2        3                                                NaN   3300000   
3        4                                                NaN   1200000   
4        5                                                NaN         0   
...    ...                                                ...       ...   
2995  2996                                                NaN         0   
2996  2997                                                NaN         0   
2997  2998                                                NaN  65000000   
2998  2999                                                NaN  42000000   
2999  3000                                                NaN  35000000   

                                                 genres  \
0                        [{'id': 35, 'name': 'Comedy'}]   
1     [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
2                         [{'id': 18, 'name': 'Drama'}]   
3     [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...   
4     [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...   
...                                                 ...   
2995  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
2996  [{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...   
2997  [{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...   
2998  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
2999  [{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...   

                               homepage    imdb_id original_language  \
0                                   NaN  tt2637294                en   
1                                   NaN  tt0368933                en   
2     http://sonyclassics.com/whiplash/  tt2582802                en   
3            http://kahaanithefilm.com/  tt1821480                hi   
4                                   NaN  tt1380152                ko   
...                                 ...        ...               ...   
2995                                NaN  tt0109403                en   
2996                                NaN  tt2364975                sv   
2997                                NaN  tt0116908                en   
2998     http://www.alongcamepolly.com/  tt0343135                en   
2999   http://www.abductionthefilm.com/  tt1600195                en   

                                original_title  \
0                       Hot Tub Time Machine 2   
1     The Princess Diaries 2: Royal Engagement   
2                                     Whiplash   
3                                      Kahaani   
4                                         마린보이   
...                                        ...   
2995                                   Chasers   
2996                               Vi är bäst!   
2997                   The Long Kiss Goodnight   
2998                          Along Came Polly   
2999                                 Abduction   

                                               overview  popularity  ...  \
0     When Lou, who has become the "father of the In...    6.575393  ...   
1     Mia Thermopolis is now a college graduate and ...    8.248895  ...   
2     Under the direction of a ruthless instructor, ...   64.299990  ...   
3     Vidya Bagchi (Vidya Balan) arrives in Kolkata ...    3.174936  ...   
4     Marine Boy is the story of a former national s...    1.148070  ...   
...                                                 ...         ...  ...   
2995  Military men Rock Reilly and Eddie Devane are ...    9.853270  ...   
2996  Three girls in 1980s Stockholm decide to form ...    3.727996  ...   
2997  Samantha Caine, suburban homemaker, is the ide...   14.482345  ...   
2998  Reuben Feffer is a guy who's spent his entire ...   15.725542  ...   
2999  A young man sets out to uncover the truth abou...   10.512109  ...   

     release_date r

In [ ]:
import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/data/imdb_data.csv")
df.head()

id                              belongs_to_collection    budget  \
0   1  [{'id': 313576, 'name': 'Hot Tub Time Machine ...  14000000   
1   2  [{'id': 107674, 'name': 'The Princess Diaries ...  40000000   
2   3                                                NaN   3300000   
3   4                                                NaN   1200000   
4   5                                                NaN         0   

                                              genres  \
0                     [{'id': 35, 'name': 'Comedy'}]   
1  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
2                      [{'id': 18, 'name': 'Drama'}]   
3  [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...   
4  [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...   

                            homepage    imdb_id original_language  \
0                                NaN  tt2637294                en   
1                                NaN  tt0368933                en   
2  http://sonyclassics.com/whiplash/  tt2582802                en   
3         http://kahaanithefilm.com/  tt1821480                hi   
4                                NaN  tt1380152                ko   

                             original_title  \
0                    Hot Tub Time Machine 2   
1  The Princess Diaries 2: Royal Engagement   
2                                  Whiplash   
3                                   Kahaani   
4                                      마린보이   

                                            overview  popularity  ...  \
0  When Lou, who has become the "father of the In...    6.575393  ...   
1  Mia Thermopolis is now a college graduate and ...    8.248895  ...   
2  Under the direction of a ruthless instructor, ...   64.299990  ...   
3  Vidya Bagchi (Vidya Balan) arrives in Kolkata ...    3.174936  ...   
4  Marine Boy is the story of a former national s...    1.148070  ...   

  release_date runtime                                   spoken_languages  \
0      2/20/15    93.0           [{'iso_639_1': 'en', 'name': 'English'}]   
1       8/6/04   113.0           [{'iso_639_1': 'en', 'name': 'English'}]   
2     10/10/14   105.0           [{'iso_639_1': 'en', 'name': 'English'}]   
3       3/9/12   122.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...   
4       2/5/09   118.0           [{'iso_639_1': 'ko', 'name': '한국어/조선말'}]   

     status                                            tagline  \
0  Released  The Laws of Space and Time are About to be Vio...   
1  Released  It can take a lifetime to find true love; she'...   
2  Released    The road to greatness can take you to the edge.   
3  Released                                                NaN   
4  Released                                                NaN   

                                      title  \
0                    Hot Tub Time Machine 2   
1  The Princess Diaries 2: Royal Engagement   
2                                  Whiplash   
3                                   Kahaani   
4                                Marine Boy   

                                            Keywords  \
0  [{'id': 4379, 'name': 'time travel'}, {'id': 9...   
1  [{'id': 2505, 'name': 'coronation'}, {'id': 42...   
2  [{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...   
3  [{'id': 10092, 'name': 'mystery'}, {'id': 1054...   
4                                                NaN   

                                                cast  \
0  [{'cast_id': 4, 'character': 'Lou', 'credit_id...   
1  [{'cast_id': 1, 'character': 'Mia Thermopolis'...   
2  [{'cast_id': 5, 'character': 'Andrew Neimann',...   
3  [{'cast_id': 1, 'character': 'Vidya Bagchi', '...   
4  [{'cast_id': 3, 'character': 'Chun-soo', 'cred...   

                                                crew   revenue  
0  [{'credit_id': '59ac067c92514107af02c8c8', 'de...  12314651  
1  [{'credit_id': '52fe43fe9251416c7502563d', 'de...  95149435  
2  [{'credit_id': '54d5356ec3a3683ba0000039', 'de...  13092000  
3  [{'credit_id': '52fe48779251

In [ ]:
#tail()--bring the rows(data point)from the bottom of data frame
df.tail()

id belongs_to_collection    budget  \
2995  2996                   NaN         0   
2996  2997                   NaN         0   
2997  2998                   NaN  65000000   
2998  2999                   NaN  42000000   
2999  3000                   NaN  35000000   

                                                 genres  \
2995  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
2996  [{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...   
2997  [{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...   
2998  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
2999  [{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...   

                              homepage    imdb_id original_language  \
2995                               NaN  tt0109403                en   
2996                               NaN  tt2364975                sv   
2997                               NaN  tt0116908                en   
2998    http://www.alongcamepolly.com/  tt0343135                en   
2999  http://www.abductionthefilm.com/  tt1600195                en   

               original_title  \
2995                  Chasers   
2996              Vi är bäst!   
2997  The Long Kiss Goodnight   
2998         Along Came Polly   
2999                Abduction   

                                               overview  popularity  ...  \
2995  Military men Rock Reilly and Eddie Devane are ...    9.853270  ...   
2996  Three girls in 1980s Stockholm decide to form ...    3.727996  ...   
2997  Samantha Caine, suburban homemaker, is the ide...   14.482345  ...   
2998  Reuben Feffer is a guy who's spent his entire ...   15.725542  ...   
2999  A young man sets out to uncover the truth abou...   10.512109  ...   

     release_date runtime                          spoken_languages    status  \
2995      4/22/94   102.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released   
2996      3/28/13   102.0  [{'iso_639_1': 'sv', 'name': 'svenska'}]  Released   
2997     10/11/96   120.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released   
2998      1/16/04    90.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released   
2999      9/22/11   106.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released   

                                                tagline  \
2995  It was supposed to be a routine prisoner trans...   
2996                                                NaN   
2997               What's forgotten is not always gone.   
2998  For the most cautious man on Earth, life is ab...   
2999          They stole his life. He's taking it back.   

                        title  \
2995                  Chasers   
2996         We Are the Best!   
2997  The Long Kiss Goodnight   
2998         Along Came Polly   
2999                Abduction   

                                               Keywords  \
2995  [{'id': 378, 'name': 'prison'}, {'id': 572, 'n...   
2996  [{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...   
2997  [{'id': 441, 'name': 'assassination'}, {'id': ...   
2998  [{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...   
2999  [{'id': 591, 'name': 'cia'}, {'id': 822, 'name...   

                                                   cast  \
2995  [{'cast_id': 2, 'character': 'Rock Reilly', 'c...   
2996  [{'cast_id': 5, 'character': 'Bobo', 'credit_i...   
2997  [{'cast_id': 10, 'character': 'Samantha Caine ...   
2998  [{'cast_id': 8, 'character': 'Reuben Feffer', ...   
2999  [{'cast_id': 2, 'character': 'Nathan Harper', ...   

                                                   crew    revenue  
2995  [{'credit_id': '52fe4494c3a368484e02ac7d', 'de...    1596687  
2996  [{'credit_id': '5716b72ac3a3686678012c84', 'de...     180590  
2997  [{'credit_id': '52fe443a9251416c7502d579', 'de...   89456761  
2998  [{'credit_id': '556f817b9251410866000a63', 'de...  171963386  
2999  [{'credit_id': '5391990d0e0a260fb5001629', 'de...   82087155  

[5 rows x 23 columns]

In [ ]:
#find the num. of rows and columns in dataframe
df.shape

(3000, 23)

In [ ]:
#find the name of all columns
df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='object')

In [ ]:
#bring the rows(data point)from the data
df.sample(5)

id                              belongs_to_collection     budget  \
1076  1077                                                NaN          0   
1007  1008                                                NaN          0   
49      50  [{'id': 115570, 'name': 'Star Trek: The Next G...   38000000   
2438  2439                                                NaN    6400000   
1972  1973  [{'id': 453993, 'name': 'The Wolverine Collect...  120000000   

                                                 genres  \
1076                      [{'id': 18, 'name': 'Drama'}]   
1007                     [{'id': 35, 'name': 'Comedy'}]   
49    [{'id': 878, 'name': 'Science Fiction'}, {'id'...   
2438  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
1972  [{'id': 28, 'name': 'Action'}, {'id': 878, 'na...   

                                     homepage    imdb_id original_language  \
1076  https://www.facebook.com/BreatheInMovie  tt1999987                en   
1007                                      NaN  tt1860180                en   
49                                        NaN  tt0111280                en   
2438                                      NaN  tt0091167                en   
1972         http://www.thewolverinemovie.com  tt1430132                en   

               original_title  \
1076               Breathe In   
1007  Billy Gardell: Halftime   
49     Star Trek: Generations   
2438   Hannah and Her Sisters   
1972            The Wolverine   

                                               overview  popularity  ...  \
1076  When a foreign exchange student arrives in a s...    6.437916  ...   
1007  Billy Gardell, the star of CBS' hit comedy "Mi...    0.007877  ...   
49    Captain Jean-Luc Picard and the crew of the En...    8.105708  ...   
2438  Between two Thanksgivings, Hannah's husband fa...    9.578740  ...   
1972  Wolverine faces his ultimate nemesis - and tes...    3.918287  ...   

     release_date runtime                          spoken_languages    status  \
1076      1/18/13    98.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released   
1007       2/5/11    60.0  [{'iso_639_1': 'en', 'name': 'English'}]   Rumored   
49       11/17/94   118.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released   
2438       2/7/86   107.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released   
1972      7/23/13   126.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released   

                                              tagline  \
1076                                              NaN   
1007                                              NaN   
49                                         Boldly go.   
2438                                              NaN   
1972  When he's most vulnerable, he's most dangerous.   

                        title  \
1076               Breathe In   
1007  Billy Gardell: Halftime   
49     Star Trek: Generations   
2438   Hannah and Her Sisters   
1972            The Wolverine   

                                               Keywords  \
1076  [{'id': 242, 'name': 'new york'}, {'id': 4217,...   
1007                                                NaN   
49    [{'id': 10988, 'name': 'based on tv series'}, ...   
2438  [{'id': 1731, 'name': 'writing'}, {'id': 2199,...   
1972  [{'id': 233, 'name': 'japan'}, {'id': 1462, 'n...   

                                                   cast  \
1076  [{'cast_id': 5, 'character': 'Keith Reynolds',...   
1007  [{'cast_id': 9, 'character': 'Himself', 'credi...   
49    [{'cast_id': 5, 'character': 'Captain Jean-Luc...   
2438  [{'cast_id': 12, 'character': 'Mickey Sachs', ...   
1972  [{'cast_id': 37, 'character': 'Logan / Wolveri...   

                                                   crew    revenue  
1076  [{'credit_id': '52fe4bfb9251416c910ebc13', 'de...      15000  
1007  [{'credit_id': '52fe4be1c3a368484e19d265', 'de...         60  
49    [{'credit_id': '52fe4225c3a36847f80076c3', 'de...  120000000  
2438  [{'credit_id': '52fe43f6c3a36847f807ab13', 'de... 

In [ ]:
#find the infromation of the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   id                     3000 non-null   int64  
 1   belongs_to_collection  604 non-null    object 
 2   budget                 3000 non-null   int64  
 3   genres                 2993 non-null   object 
 4   homepage               946 non-null    object 
 5   imdb_id                3000 non-null   object 
 6   original_language      3000 non-null   object 
 7   original_title         3000 non-null   object 
 8   overview               2992 non-null   object 
 9   popularity             3000 non-null   float64
 10  poster_path            2999 non-null   object 
 11  production_companies   2844 non-null   object 
 12  production_countries   2945 non-null   object 
 13  release_date           3000 non-null   object 
 14  runtime                2998 non-null   float64
 15  spok

In [ ]:
#How does the data look like
df.describe()

id        budget   popularity      runtime       revenue
count  3000.000000  3.000000e+03  3000.000000  2998.000000  3.000000e+03
mean   1500.500000  2.253133e+07     8.463274   107.856571  6.672585e+07
std     866.169729  3.702609e+07    12.104000    22.086434  1.375323e+08
min       1.000000  0.000000e+00     0.000001     0.000000  1.000000e+00
25%     750.750000  0.000000e+00     4.018053    94.000000  2.379808e+06
50%    1500.500000  8.000000e+06     7.374861   104.000000  1.680707e+07
75%    2250.250000  2.900000e+07    10.890983   118.000000  6.891920e+07
max    3000.000000  3.800000e+08   294.337037   338.000000  1.519558e+09

In [ ]:
#find the duplicate value
df.duplicated().sum()

np.int64(0)

In [ ]:
df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='object')

In [ ]:
#find the null value
df.isnull().sum()

id                          0
belongs_to_collection    2396
budget                      0
genres                      7
homepage                 2054
imdb_id                     0
original_language           0
original_title              0
overview                    8
popularity                  0
poster_path                 1
production_companies      156
production_countries       55
release_date                0
runtime                     2
spoken_languages           20
status                      0
tagline                   597
title                       0
Keywords                  276
cast                       13
crew                       16
revenue                     0
dtype: int64

In [ ]:
#slicing and indexing
#find the single column with all rows
df["title"]

0                         Hot Tub Time Machine 2
1       The Princess Diaries 2: Royal Engagement
2                                       Whiplash
3                                        Kahaani
4                                     Marine Boy
                          ...                   
2995                                     Chasers
2996                            We Are the Best!
2997                     The Long Kiss Goodnight
2998                            Along Came Polly
2999                                   Abduction
Name: title, Length: 3000, dtype: object

In [ ]:
#multpile column with all rows
df[["title","budget","revenue",'original_language']]

title    budget    revenue  \
0                       Hot Tub Time Machine 2  14000000   12314651   
1     The Princess Diaries 2: Royal Engagement  40000000   95149435   
2                                     Whiplash   3300000   13092000   
3                                      Kahaani   1200000   16000000   
4                                   Marine Boy         0    3923970   
...                                        ...       ...        ...   
2995                                   Chasers         0    1596687   
2996                          We Are the Best!         0     180590   
2997                   The Long Kiss Goodnight  65000000   89456761   
2998                          Along Came Polly  42000000  171963386   
2999                                 Abduction  35000000   82087155   

     original_language  
0                   en  
1                   en  
2                   en  
3                   hi  
4                   ko  
...                ...  
2995                en  
2996                sv  
2997                en  
2998                en  
2999                en  

[3000 rows x 4 columns]

from matplotlib import pyplot as plt
_df_0['budget'].plot(kind='hist', bins=20, title='budget')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['revenue'].plot(kind='hist', bins=20, title='revenue')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2.plot(kind='scatter', x='budget', y='revenue', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['budget'].plot(kind='line', figsize=(8, 4), title='budget')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_4['revenue'].plot(kind='line', figsize=(8, 4), title='revenue')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
#slicing with help of rows
df[0:4]

id                              belongs_to_collection    budget  \
0   1  [{'id': 313576, 'name': 'Hot Tub Time Machine ...  14000000   
1   2  [{'id': 107674, 'name': 'The Princess Diaries ...  40000000   
2   3                                                NaN   3300000   
3   4                                                NaN   1200000   

                                              genres  \
0                     [{'id': 35, 'name': 'Comedy'}]   
1  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
2                      [{'id': 18, 'name': 'Drama'}]   
3  [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...   

                            homepage    imdb_id original_language  \
0                                NaN  tt2637294                en   
1                                NaN  tt0368933                en   
2  http://sonyclassics.com/whiplash/  tt2582802                en   
3         http://kahaanithefilm.com/  tt1821480                hi   

                             original_title  \
0                    Hot Tub Time Machine 2   
1  The Princess Diaries 2: Royal Engagement   
2                                  Whiplash   
3                                   Kahaani   

                                            overview  popularity  ...  \
0  When Lou, who has become the "father of the In...    6.575393  ...   
1  Mia Thermopolis is now a college graduate and ...    8.248895  ...   
2  Under the direction of a ruthless instructor, ...   64.299990  ...   
3  Vidya Bagchi (Vidya Balan) arrives in Kolkata ...    3.174936  ...   

  release_date runtime                                   spoken_languages  \
0      2/20/15    93.0           [{'iso_639_1': 'en', 'name': 'English'}]   
1       8/6/04   113.0           [{'iso_639_1': 'en', 'name': 'English'}]   
2     10/10/14   105.0           [{'iso_639_1': 'en', 'name': 'English'}]   
3       3/9/12   122.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...   

     status                                            tagline  \
0  Released  The Laws of Space and Time are About to be Vio...   
1  Released  It can take a lifetime to find true love; she'...   
2  Released    The road to greatness can take you to the edge.   
3  Released                                                NaN   

                                      title  \
0                    Hot Tub Time Machine 2   
1  The Princess Diaries 2: Royal Engagement   
2                                  Whiplash   
3                                   Kahaani   

                                            Keywords  \
0  [{'id': 4379, 'name': 'time travel'}, {'id': 9...   
1  [{'id': 2505, 'name': 'coronation'}, {'id': 42...   
2  [{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...   
3  [{'id': 10092, 'name': 'mystery'}, {'id': 1054...   

                                                cast  \
0  [{'cast_id': 4, 'character': 'Lou', 'credit_id...   
1  [{'cast_id': 1, 'character': 'Mia Thermopolis'...   
2  [{'cast_id': 5, 'character': 'Andrew Neimann',...   
3  [{'cast_id': 1, 'character': 'Vidya Bagchi', '...   

                                                crew   revenue  
0  [{'credit_id': '59ac067c92514107af02c8c8', 'de...  12314651  
1  [{'credit_id': '52fe43fe9251416c7502563d', 'de...  95149435  
2  [{'credit_id': '54d5356ec3a3683ba0000039', 'de...  13092000  
3  [{'credit_id': '52fe48779251416c9108d6eb', 'de...  16000000  

[4 rows x 23 columns]

In [ ]:
#find somw  numbwr of rows and columns
df.iloc[0:4,0:3]

id                              belongs_to_collection    budget
0   1  [{'id': 313576, 'name': 'Hot Tub Time Machine ...  14000000
1   2  [{'id': 107674, 'name': 'The Princess Diaries ...  40000000
2   3                                                NaN   3300000
3   4                                                NaN   1200000

In [ ]:
from transformers import pipeline
summarize=pipeline("summarizationl",model="facebook/bart-large-cnn")
text="""the global shift toward renewable energy is acceleraitng,driven by concerns over climate change and energy security.Solar and wind power installations have reached record levels worldwide."""

summary = summarizer(text, max_length=30, min_length=10, do_sample=False)
print(summary[0])

config.json: 0.00B [00:00, ?B/s]

KeyError: "Unknown task summarizationl, available tasks are ['audio-classification', 'automatic-speech-recognition', 'depth-estimation', 'document-question-answering', 'feature-extraction', 'fill-mask', 'image-classification', 'image-feature-extraction', 'image-segmentation', 'image-text-to-text', 'image-to-image', 'image-to-text', 'keypoint-matching', 'mask-generation', 'ner', 'object-detection', 'question-answering', 'sentiment-analysis', 'summarization', 'table-question-answering', 'text-classification', 'text-generation', 'text-to-audio', 'text-to-speech', 'text2text-generation', 'token-classification', 'translation', 'video-classification', 'visual-question-answering', 'vqa', 'zero-shot-audio-classification', 'zero-shot-classification', 'zero-shot-image-classification', 'zero-shot-object-detection', 'translation_XX_to_YY']"

In [ ]:
my_list=[10,20,30,40,50]
print(my_list)


[10, 20, 30, 40, 50]


In [ ]:
my_list.append(60)
print(my_list)

[10, 20, 30, 40, 50, 50, 50, 60, 60, 60, 60]


In [ ]:
my_list.remove(60)
print(my_list)

[10, 20, 30, 40, 50, 50, 50, 60, 60]


In [ ]:
my_list.insert(3,70)
print(my_list)

[10, 20, 30, 70, 70, 40, 50, 50, 50, 60, 60]


In [ ]:
removed_item=my_list.pop
print("removed item",removed_item)
print(my_list)

removed item <built-in method pop of list object at 0x79b5ad0cb380>
[10, 20, 30, 70, 70, 40, 50, 50, 50, 60, 60]


In [ ]:
my_list.pop(4)
print(my_list)

[10, 20, 30, 70, 50, 50, 50, 60, 60]


In [ ]:
print(my_list[1:3])

[20, 30]


In [ ]:
print(my_list[:2])

[10, 20]


In [ ]:
print(my_list[2:])

[30, 70, 50, 50, 50, 60, 60]


In [ ]:
print(my_list[6:])

[50, 60, 60]


In [ ]:
#clear=remove all the items from the list
my_list=[10,20,30,40,50,60]
my_list.clear()
print(my_list)

[]
